### ISSUE TITLE
Add Cart Page

### ISSUE THREAD

**Issue by shailifadadu** [khushi-joshi-05/Food-ordering-website#18]
Cart page is not there.

**Comment by kanikaa-3018** [comment]
pls assign this issue to me for GSSoc'24( in cart section signup,signin and place order other options will be added)

**Comment by mrskjha** [comment]
I can do Card section this so please assign me for GSSoC.

**Comment by u-s-h-a** [comment]
please assign me this issue under GSSOC'24 i will link another page to cart section

**Comment by urgetolearn** [comment]
hey @shailifadadu I would love to add a cart page, please assign this task to me under gssoc'24.
picture for reference:
![image](https://github.com/khushi-joshi-05/Food-ordering-website/assets/131844481/bd175f11-2f68-412f-ae67-cb469ecb9710)

**Comment by Sneha123-zudo** [comment]
I am interested in solving this issue, please assign me this issue under GSSOC'24

**Comment by rishyym0927** [comment]
Hi,

I am a contributor in GSSoC'24. I want to work on this issue. I have experience in web development and Im sure that I can fix this issue

Thanks

**Comment by 1911aditi** [comment]
hii 
i have experience in frontend n i m can fix this issue also I want to contribute in GSSoc'24. So pls assign me

**Comment by Pujan-sarkar** [comment]
I can contribute in this issue under GSSOC"24 , @khushi-joshi-05  will you assign this problem to me

**Comment by Drona-Srivastava** [comment]
Hi, I am a Contributor under GSSoC 24.
I have started working on this issue, i have added the basic template.
Please @khushi-joshi-05  assign me this issue so that i can create a PR.

**Comment by Drona-Srivastava** [comment]
Hi, I am a Contributor under GSSoC 24.
I have started working on this issue, i have added the basic template.
Please @khushi-joshi-05  assign me this issue so that i can create a PR.

This is my update so far i can help with this as i have experience with HTML CSS and planning to add some features using JS as well to this.

![Screenshot 2024-05-11 131509](https://github.com/khushi-joshi-05/Food-ordering-website/assets/120251095/db2061a0-2935-411e-b3a1-a5c94983b60a)

**Comment by shrutibharat-05** [comment]
Hey since I am proficient  in UI and HTML,CSS  and Js. Please assign this to me

**Comment by jency1** [comment]
I'm ready to tackle the Cart Page addition as I have experience in this. Kindly assign this task to me and I'll make sure it's done efficiently.

**Comment by Drona-Srivastava** [comment]
@khushi-joshi-05  Please assign me this issue under GSSoC 24 i have already started working in it. I have already added an update above please have a look and assign me the issue.

**Comment by shailifadadu** [comment]
@urgetolearn I am not associated to the project ,So how would I assign you the issue 😅 You should check who is the project admin for the project and tag them.

**Comment by khushi-joshi-05** [comment]
@Drona-Srivastava  this issue has already been solved. Thanks for showing interest. You can work on some other issue.

**Comment by Drona-Srivastava** [comment]
@khushi-joshi-05 Sure, No Problem

**Comment by kesava23** [comment]
Hi there, I'm a beginner at open-source contribution so I want to gain hands-on experience by contributing to this project through GSSOC'24. Please assign this issue to me. Thank you.

**Comment by Drona-Srivastava** [comment]
@kesava23 this issue is already resolved check the repo. You can work on some other issue or just clone the site on your local system and open up the site and look for any issue that you think should be solved ask to get assigned if already there or create a new issue and start working ok it once assigned
