### ISSUE TITLE
Add Contact Us page

### ISSUE THREAD

**Issue by pankaj-bind** [khushi-joshi-05/Food-ordering-website#25]
Proposed update:
Contact us page is not implemented. I can implement contact us page.
Please assign me this work.

**Comment by harshmishra19** [comment]
Hello @khushi-joshi-05 Can you plz assign this issue to me under GSSOC'24

**Comment by MehekFatima** [comment]
Hi @khushi-joshi-05 ,

I hope this message finds you well. I'm excited to express my interest in contributing to the GSSOC project and would like to request assignment of the issue titled "Add Contact Us page"

Having reviewed the issue description, I'm confident in my ability to make a meaningful contribution towards resolving it. Could you please confirm if this issue is available for assignment?

I'm looking forward to the opportunity to contribute to the project

**Comment by ranjumaheshwari** [comment]
I would wish to contribute to this part 
I think i can make it better..

**Comment by FatemaBaig** [comment]
Hello sir,
i would like to work on this part of project. Please assign it to me.

**Comment by harshitayadavv** [comment]
Hi @khushi-joshi-05 ! I'm excited to take on the "Contact Us" task. This involves refining the way users can reach out to us. I'll be working on creating a straightforward contact form where users can easily drop their questions, suggestions, or concerns. My aim is to make it hassle-free for them to connect with us, ensuring the process is smooth and hassle-free
