### ISSUE TITLE
Navbar Issue

### ISSUE THREAD

**Issue by Abhishek0732** [khushi-joshi-05/Food-ordering-website#32]
I want to fix the navbar which does not contains the menu page, contact page and services.

**Comment by Ridhima10** [comment]
I am contributing under Gssoc'24
I would like to enhance the navbar by :
- adding navigation to the links of navbar so that we can surf through all the pages
- Adding a new hover effect for better  UI
- Changing position of navbar. (Since there is nothing on right side of navbar so it will be better to make position of list items center)

**Comment by mdramijzamadar** [comment]
i would like to fix this problem . Please assign to me.

**Comment by KunjMaheshwari** [comment]
@Abhishek0732 I am contributing under Gssoc'24
I would like to enhance the navbar by :

adding navigation to the links of navbar so that we can surf through all the pages
Adding a new hover effect for better UI
Changing position of navbar. (Since there is nothing on right side of navbar so it will be better to make position of list items center)
Please assign me this issue
Best Regards

**Comment by Ridhima10** [comment]
@KunjMaheshwari  have the creativity to write it yourself. Why are you copying my ideas even word to word?

**Comment by aanchalpahuja18** [comment]
@khushi-joshi-05 I can do this. Kindly assign me this issue

**Comment by sunny0625** [comment]
This issue is already solved.
Try to contribute to different issues.
