### ISSUE TITLE
UI enhancement of footer 

### ISSUE THREAD

**Issue by GarimaSingh0109** [khushi-joshi-05/Food-ordering-website#423]
There is a UI bug in the web page the download buttons collide with the headings of the the footer. It makes it inconvenient for the user to read. It will give bad user experience as it will be difficult to navigate through.

The download links need to be separated from  the footer links.

@khushi-joshi-05 I have experience of fixing such issues. I can solve this bug to enhance the UI of the website. I am willing to contribute to this project. Kindly assign me this project under gssoc'24

<img width="934" alt="foodie_issue" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/130893914/20187485-2824-435b-a482-87557f6af5c8">

**Comment by Rishitatripathi** [comment]
I would like to work on this issue, Please assign it to me under GSSOC 2024

**Comment by khushi-joshi-05** [comment]
@GarimaSingh0109 Ihave assigned u this issue

**Comment by jency1** [comment]
> @GarimaSingh0109 Ihave assigned u this issue

@khushi-joshi-05 I raised this issue three days ago, #403  yet it has not been assigned to me. Instead, it has been assigned to someone else who raised the issue today. Given that we operate on a first-come, first-serve basis, this situation seems unfair.

I would appreciate it if you could review this matter and consider reassigning the issue to me, as I have been awaiting its allocation since I first raised it.
