### ISSUE TITLE
Improving Contact us in the footer

### ISSUE THREAD

**Issue by MattipaPoojitha** [khushi-joshi-05/Food-ordering-website#46]
@khushi-joshi-05  In the existing System the website need the user to provide the emai Id and message which can be improved by just adding a email icon and once the user clicks on it it will redirect to their original mail account to thus making it more efficient.
Kindly accept my contribution.
Thank you 😊!

**Comment by SIM-RAITANI** [comment]
Ma'am i would like to contribute to this. Contact us is a very crucial part of the website. Not getting enough information about the company becomes a pain point for the customers. Apart from email ,there should be a phone number so that user don't have to wait for hours to get a response. Apart from the email of customer ,we can also ask their mobile number. 

I would love to work on this.

**Comment by GarimaSingh0109** [comment]
i would like to contribute to this project kindly assign me the task under #gssoc'24

**Comment by sahithinandikula** [comment]
I interested in working on this .please assign this issue

**Comment by Aishikap** [comment]
I would like to work on this issue. please assign me under gssoc'24

**Comment by shnwz-solves** [comment]
Hey PA, I want to contribute, please assign this issue to me. Thankyou!
