### ISSUE TITLE
[BUG]: On hover upper border gets hidden beneath the image above it (manage hovering effect)

### ISSUE THREAD

**Issue by SwatiAgwl** [khushi-joshi-05/Food-ordering-website#543]
<img width="1146" alt="Screenshot 2024-05-26 at 11 40 56 AM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/147516772/de284d54-e7ab-4469-9aa4-ed0a832f5147">
The hovering effect/scale should be corrected and also can reduce card size for a better UI.

<img width="1391" alt="Screenshot 2024-05-26 at 11 43 27 AM" src="https://github.com/khushi-joshi-05/Food-ordering-website/assets/147516772/988484be-f657-47a0-bb12-f910f9817ca6">
Cards should be of similar and slightly small sized for an appealing UI.

Kindly assign this issue to me under GSSOC'24.
Thanks!

**Comment by Dilip-Kashyp** [comment]
Hi @SwatiAgwl @khushi-joshi-05 ,

I'd like to take on this issue and provide a solution. I believe the problem can be fixed by adjusting the `z-index` and `position` properties in the CSS to ensure the upper border remains visible on hover. Could you please assign this issue to me? Thank you!

Best regards,
[Dilip Kumar]

**Comment by Dilip-Kashyp** [comment]
![Screenshot 2024-05-26 141801](https://github.com/khushi-joshi-05/Food-ordering-website/assets/108999605/fb7d94bd-8c18-4518-a543-f001a964c9f4)
Hi @sunny0625 , @khushi-joshi-05, 
Could you please review the PR and let me know if any adjustments are needed?
